In [1]:
import numpy as np

In [2]:
l = list(range(10))
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [3]:
#list of strings 

l2 = [str(c) for c in l ]
print(l2)

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']


In [4]:
l3 = [1,'piyal',2.34324, False]
[type(item) for item in l3]

[int, str, float, bool]

Array in Python

In [5]:
import array


In [6]:
l= list(range(10))
a= array.array('i',l) # here  'i' is indecating that contents of 'l' ar integers
print(a)

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


Initializing multidimensional array using list of lists

In [7]:
np.array([range(i,i+5) for i in [2,4,6]])

array([[ 2,  3,  4,  5,  6],
       [ 4,  5,  6,  7,  8],
       [ 6,  7,  8,  9, 10]])

In [8]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.full((3,5), 3.1416)

array([[3.1416, 3.1416, 3.1416, 3.1416, 3.1416],
       [3.1416, 3.1416, 3.1416, 3.1416, 3.1416],
       [3.1416, 3.1416, 3.1416, 3.1416, 3.1416]])

In [10]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
# creating ar array by linear sequence 
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
#creating an array of five values evenly spaced between 0 and 1 
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
# Array with random values 
np.random.random((3,3))

array([[0.99475108, 0.07618443, 0.36527421],
       [0.6545214 , 0.89970557, 0.90154653],
       [0.10497684, 0.31565363, 0.97646735]])

In [14]:
# 3 * 3 array of normally distributed random values 
# with mean 0 and standerd deviation 1 

np.random.normal(0,1,(3,3))

array([[ 0.50121046,  1.60461727,  1.67365827],
       [-1.73172234,  1.12589463,  1.15401452],
       [ 0.06033835, -1.50223107,  0.78691117]])

In [15]:
# 3 * 3 array of random integers from 0 - 10 
np.random.randint(0,10,(3,3))

array([[2, 6, 3],
       [4, 3, 4],
       [2, 6, 9]])

In [16]:
# 3 * 3 identity matrix 
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
# another way of creating array
c = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(c)
print(c.ndim)  #prints the dimension of the array

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
3


Many dimensions

In [18]:
#creating more than 3 dimension array
#as many dimension as  one need 

many_dim= np.array([1,2,3,4],ndmin=10)
print(many_dim)
print('dimension of the array :' ,many_dim.ndim)
type(many_dim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
dimension of the array : 10


numpy.ndarray