In [1]:
import numpy as np


In [2]:
np.random.seed(0)
x1 = np.random.randint(10, size =6)         #one - dimensional
x2 = np.random.randint(10, size = (3,4))    #two - dimensional
x3 = np.random.randint(10, size = (3,4,5))  #three - dimensional

In [3]:
print('x3 Dimension ', x3.ndim)
print('x3 Shape', x3.shape)
print('x3 Size ',x3.size)
print('Data type - ' , x3.dtype)

x3 Dimension  3
x3 Shape (3, 4, 5)
x3 Size  60
Data type -  int32


Array Indexing : Accessing single elements 

In [4]:
x1

array([5, 0, 3, 3, 7, 9])

In [5]:
x1[0] # first element

5

In [6]:
#negetive indexing to access last element 
x1[-1]  

9

In [7]:
#2nd last index
x1[-2]

7

In [8]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [9]:
# in multidimensional array access elements with comma separeted tuple indices 
# row and column index starts from 0 

x2[ 0,0]

3

In [10]:
x2[2,3]       # 2 - row number  , 3- column number 

7

In [11]:
# we can use negetive indexes also 
x2 [ 2, -1]

7

In [12]:
# changing the values of the array 

x2[ 0,0 ]= 12
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


Array Slicing -> Accessing Subarrays

Array [ start : stop : step]

In [13]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
a [ : 5] # first five elements 

array([0, 1, 2, 3, 4])

In [15]:
a [5:] # elements after index 5

array([5, 6, 7, 8, 9])

In [16]:
a[ 4 : 7 ] # middle values from 4 -> 6 

array([4, 5, 6])

In [17]:
# every element with gap of  2
a[ ::2]

array([0, 2, 4, 6, 8])

In [18]:
#every element with gap of 1 start from -> 1
a [ 1 :: 2]

array([1, 3, 5, 7, 9])

Negetive indexing 

In [19]:
a [ :: -1] # revese of an array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [20]:
a [ 5 :: -2]  # reverse evey other from index 5

array([5, 3, 1])

In [21]:
a[ :: 2]

array([0, 2, 4, 6, 8])

In [22]:
a [  -5 : ]

array([5, 6, 7, 8, 9])

Multidimensional Subarrays

In [23]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [24]:
# getting specific row 
x2[ 0,:]

array([12,  5,  2,  4])

In [25]:
#getting specific column
x2 [ :, 3]

array([4, 8, 7])

In [26]:
x2 [ :2 , :3]  # two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [27]:
x2 [ :, ::2]  # all row column from 1 with gap of 2

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [28]:
#reverse dimensions 
x2[ ::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

Sub_Array as no copy Views

In [29]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [30]:
#extracting a 2 * 2 sub_array from x2

sub_x2 = x2[:2,:2]
print(sub_x2)

[[12  5]
 [ 7  6]]


In [31]:
# if we make any change in the sub array [ sub_x2]
# the value in the main arrya will change . 

sub_x2[0,0] = 99
print(sub_x2)

[[99  5]
 [ 7  6]]


In [32]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


To avoid this we use Copy() Function 

In [33]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [34]:
copy_x2=  x2[:2,:2].copy()
print(copy_x2)

[[99  5]
 [ 7  6]]


In [35]:
copy_x2[0,0 ]= 111
print(copy_x2)

[[111   5]
 [  7   6]]


In [36]:
print(x2)
#the main array did not change. 

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
