Reshaping of Arrays 

In [1]:
import numpy as np

In [2]:
np.random.seed(0)
x1 = np.random.randint(10, size =6)         #one - dimensional
x2 = np.random.randint(10, size = (3,4))    #two - dimensional
x3 = np.random.randint(10, size = (3,4,5))  #three - dimensional

In [3]:
print(x1)

[5 0 3 3 7 9]


In [4]:
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [5]:
print(x3)

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


Reshaping of Arrays


In [6]:
#using the reshape() function 

grid = np.arange(1,10).reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
x= np.array([1,2,3])
x

array([1, 2, 3])

In [8]:
x.reshape((3,1))  # reshape by column

array([[1],
       [2],
       [3]])

In [9]:
x.reshape((1,3)) #reshape by row

array([[1, 2, 3]])

In [10]:
#column vector by newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

Arrays Concatination and Spliting 

Concatination :

In [11]:
x= np.array([1,2,3])
y = np.array([4,5,6])

np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [12]:
#adding more than two arrya together 
z=np.array([99,99,99])

np.concatenate([x,y,z])

array([ 1,  2,  3,  4,  5,  6, 99, 99, 99])

In [13]:
#can add two dimensional array also

np.concatenate([grid,grid])


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
#concatinate along the second axis
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [15]:
#using vertical stack . and horizontal stack 

x= np.array([77,77,77])
np.vstack([x,grid])


array([[77, 77, 77],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [16]:
k = np.array([[99],[99],[99]])

In [17]:
#using horizontal stack 
np.hstack([k,grid])

array([[99,  1,  2,  3],
       [99,  4,  5,  6],
       [99,  7,  8,  9]])

In [18]:
np.hstack([grid,k])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99],
       [ 7,  8,  9, 99]])

Splitting:

In [19]:
x = [1,2,3,99,99, 3,2,1]
x1,x2,x3 = np.split(x,[3,5])
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


In [20]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [21]:
upper,lower = np.vsplit(grid,[2])
print(upper)
print()
print(lower)

[[0 1 2 3]
 [4 5 6 7]]

[[ 8  9 10 11]
 [12 13 14 15]]


In [22]:
left, right = np.hsplit(grid,[2])
print(left)
print()
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
