In [1]:
import numpy as np

In [4]:
arr  = np.random.randint(1,10,(3,4))

In [5]:
arr

array([[7, 6, 9, 4],
       [7, 7, 2, 3],
       [7, 8, 2, 7]])

In [6]:
arr.reshape(6,2)

array([[7, 6],
       [9, 4],
       [7, 7],
       [2, 3],
       [7, 8],
       [2, 7]])

In [7]:
arr.reshape(2,6)

array([[7, 6, 9, 4, 7, 7],
       [2, 3, 7, 8, 2, 7]])

**We can reshape the array if the new array is same as the old one. Our 1st array was 3 * 4 =12 values new one is 6 * 2 =12 and 2*6=12**

In [8]:
arr.T

array([[7, 7, 7],
       [6, 7, 8],
       [9, 2, 2],
       [4, 3, 7]])

In [10]:
arr.flatten()

array([7, 6, 9, 4, 7, 7, 2, 3, 7, 8, 2, 7])

In [11]:
arr1 = np.array([1,2,3,4,5])

In [14]:
arr1.ndim

1

In [16]:
np.expand_dims(arr1 , axis=1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [17]:
# -> making a 1 dimensional array from 2 using squeeze operation 

data = np.array([[1],[2],[3]])
data

array([[1],
       [2],
       [3]])

In [18]:
np.squeeze(data)

array([1, 2, 3])

In [19]:
# -> shifting array elements
arr1

array([1, 2, 3, 4, 5])

In [20]:
np.roll(arr1,2)

array([4, 5, 1, 2, 3])

In [21]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

**BINARY OPERATION**

In [32]:
arr1 = np.random.randint(1,10,(3,4))

In [23]:
arr2 = np.random.randint(1,10,(3,4))

In [24]:
arr1 

array([[3, 7, 3, 6],
       [6, 1, 8, 3],
       [3, 1, 7, 2]])

In [25]:
arr2

array([[8, 1, 4, 5],
       [8, 6, 6, 6],
       [8, 9, 9, 5]])

In [26]:
arr1 + arr2

array([[11,  8,  7, 11],
       [14,  7, 14,  9],
       [11, 10, 16,  7]])

In [27]:
arr1 * arr2 

array([[24,  7, 12, 30],
       [48,  6, 48, 18],
       [24,  9, 63, 10]])

In [28]:
arr1 / arr2

array([[0.375     , 7.        , 0.75      , 1.2       ],
       [0.75      , 0.16666667, 1.33333333, 0.5       ],
       [0.375     , 0.11111111, 0.77777778, 0.4       ]])

In [29]:
arr1 % arr2

array([[3, 0, 3, 1],
       [6, 1, 2, 3],
       [3, 1, 7, 2]], dtype=int32)

In [30]:
arr1 ** arr2

array([[    6561,        7,       81,     7776],
       [ 1679616,        1,   262144,      729],
       [    6561,        1, 40353607,       32]], dtype=int32)

**Binary AND operation**

In [31]:
arr1 & arr2

array([[0, 1, 0, 4],
       [0, 0, 0, 2],
       [0, 1, 1, 0]], dtype=int32)

**OR OPERATION**

In [33]:
arr1 | arr2

array([[ 9,  5,  5, 13],
       [14,  6,  7,  7],
       [12, 13, 13,  7]], dtype=int32)

In [34]:
arr1 > arr2

array([[False,  True, False,  True],
       [False, False,  True, False],
       [False, False, False, False]])

**CHAR CLASS**

In [37]:
name = np.array(['piyal','ahmed'])

In [38]:
np.char.upper(name)

array(['PIYAL', 'AHMED'], dtype='<U5')

In [39]:
np.char.title(name)

array(['Piyal', 'Ahmed'], dtype='<U5')

In [40]:
np.char.capitalize(name)

array(['Piyal', 'Ahmed'], dtype='<U5')

**MATHEMATICAL**

In [41]:
arr1

array([[1, 4, 1, 9],
       [6, 4, 7, 3],
       [4, 5, 5, 2]])

In [42]:
np.sin(arr1)

array([[ 0.84147098, -0.7568025 ,  0.84147098,  0.41211849],
       [-0.2794155 , -0.7568025 ,  0.6569866 ,  0.14112001],
       [-0.7568025 , -0.95892427, -0.95892427,  0.90929743]])

In [43]:
np.cos(arr1)

array([[ 0.54030231, -0.65364362,  0.54030231, -0.91113026],
       [ 0.96017029, -0.65364362,  0.75390225, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.28366219, -0.41614684]])

In [44]:
np.tan(arr1)

array([[ 1.55740772,  1.15782128,  1.55740772, -0.45231566],
       [-0.29100619,  1.15782128,  0.87144798, -0.14254654],
       [ 1.15782128, -3.38051501, -3.38051501, -2.18503986]])

In [45]:
np.tanh(arr1)

array([[0.76159416, 0.9993293 , 0.76159416, 0.99999997],
       [0.99998771, 0.9993293 , 0.99999834, 0.99505475],
       [0.9993293 , 0.9999092 , 0.9999092 , 0.96402758]])

In [46]:
np.exp(arr2)

array([[2.98095799e+03, 2.71828183e+00, 5.45981500e+01, 1.48413159e+02],
       [2.98095799e+03, 4.03428793e+02, 4.03428793e+02, 4.03428793e+02],
       [2.98095799e+03, 8.10308393e+03, 8.10308393e+03, 1.48413159e+02]])

In [47]:
np.sqrt(arr2)

array([[2.82842712, 1.        , 2.        , 2.23606798],
       [2.82842712, 2.44948974, 2.44948974, 2.44948974],
       [2.82842712, 3.        , 3.        , 2.23606798]])

In [48]:
np.power(arr1,2)

array([[ 1, 16,  1, 81],
       [36, 16, 49,  9],
       [16, 25, 25,  4]], dtype=int32)

In [49]:
np.mean(arr2)

6.25

In [50]:
np.median(arr1)

4.0

In [51]:
np.std(arr2)

2.2407216099581255

In [52]:
np.var(arr1)

5.1875

In [53]:
np.min(arr2)

1

In [54]:
np.max(arr2)

9

# [ Sorting , Searching ,Counting ]

In [55]:
np.sort(arr1)

# -> It will sort row by row 

array([[1, 1, 4, 9],
       [3, 4, 6, 7],
       [2, 4, 5, 5]])

In [56]:
arr1

array([[1, 4, 1, 9],
       [6, 4, 7, 3],
       [4, 5, 5, 2]])

In [57]:
np.sort(arr2)

array([[1, 4, 5, 8],
       [6, 6, 6, 8],
       [5, 8, 9, 9]])

In [58]:
arr2

array([[8, 1, 4, 5],
       [8, 6, 6, 6],
       [8, 9, 9, 5]])

In [60]:
k = np.array([1,2,3,0,0,0,0,123,12,23,23,3])

In [61]:
np.count_nonzero(k)

8

In [62]:
np.where(k > 6)

(array([ 7,  8,  9, 10], dtype=int64),)

In [65]:
np.extract(k > 3,k )

array([123,  12,  23,  23])

In [66]:
np.extract(arr1 > 3, arr1)

array([4, 9, 6, 4, 7, 4, 5, 5])

**COPY**

In [68]:
p = np.array([1,2,4,3,5,6,33,464,643,9])

In [74]:
# -> Deep Copy

a = np.copy(p)

In [70]:
a

array([  1,   2,   4,   3,   5,   6,  33, 464, 643,   9])

In [72]:
a[3] = 99999
a

array([    1,     2,     4, 99999,     5,     6,    33,   464,   643,
           9])

In [73]:
p

array([  1,   2,   4,   3,   5,   6,  33, 464, 643,   9])

In [79]:
# -> swallow copy 

b = p.view()

In [77]:
b[1] = 999
b

array([  1, 999,   4,   3,   5,   6,  33, 464, 643,   9])

In [78]:
p

array([  1, 999,   4,   3,   5,   6,  33, 464, 643,   9])

**MATRIX LIBRARY**

In [80]:
import numpy.matlib as nm

In [81]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [82]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [83]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

**LINEAR ALGEBRA**

In [87]:
arr3 = np.random.randint([[2,3],[4,5]])

In [88]:
arr4 = np.random.randint([[5,3],[2,5]])

In [89]:
np.dot(arr3,arr4)

array([[3, 2],
       [3, 4]])