In [45]:
import numpy as np


In [46]:
arr = np.array([1,2,3,4,5,6,7,8])
x= arr.reshape(2,4)
print(x)

[[1 2 3 4]
 [5 6 7 8]]


In [47]:
x = arr.reshape(4,2)
print(x)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [48]:
x=arr.reshape(8,1)
print(x)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [49]:
arr1 = np.array([1,2,3,4,5,6])
print(arr1.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [50]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
np.reciprocal(arr)

array([1, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [52]:
print('min: ',np.min(arr),np.argmin(arr))
print('max: ',np.max(arr),np.argmax(arr))

min:  1 0
max:  9 8


In [53]:
y = np.array([1,2,3])
print(y.cumsum())

 # -> First value stays same            ->1
 # -> 2nd value(x) = 1st  + 2nd value   -> 1+2 = 3
 # -> 3rd vaue  =  x + 3rd value        ->3 + 3 = 6
 
 #usecase of cumsum : statistics 

[1 3 6]


In [54]:
y1 = np.array([1,2,3,4])
print(y1.cumsum())

[ 1  3  6 10]


In [55]:
type(y1)
print()
print(np.shape(y1))


(4,)


In [56]:
z = np.array([1,2,3,4,5,6,7,8])

for i in z:
    print(i)
  

1
2
3
4
5
6
7
8


In [57]:
#iterating 2D array

z1= np.array([[1,2,3,4],[5,6,7,8]])
print('your array is :')
print(z1)

print()

for k in z1:
    print(k)
    
    
print()


for k in z1:
    for i in k:
        print(i)

your array is :
[[1 2 3 4]
 [5 6 7 8]]

[1 2 3 4]
[5 6 7 8]

1
2
3
4
5
6
7
8


In [58]:
#using built in function to iterate through array 

for i in np.nditer(z1):
    print(i)


1
2
3
4
5
6
7
8


In [59]:
x = np.array([[1,2],[3,4]])
y = np.array([[1,2],[3,4]])

z = np.concatenate((x,y),axis=0)


print(x)
print()
print(y)
print()


print(z)

[[1 2]
 [3 4]]

[[1 2]
 [3 4]]

[[1 2]
 [3 4]
 [1 2]
 [3 4]]


In [60]:
print(arr)

[1 2 3 4 5 6 7 8 9]


In [63]:
x= np.where((arr%2) == 0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [64]:
x = np.array([1,4,234,52,323,5,2,23,2,45])
print(np.sort(x))

[  1   2   2   4   5  23  45  52 234 323]


In [66]:
print(x.sort())

None


In [69]:
var = np.array([1,2,3,4,5,6])

y = np.resize(var,(3,2))
print(y)

print()

print(y.flatten(order='F'))

print()
print(y.flatten(order='C'))

[[1 2]
 [3 4]
 [5 6]]

[1 3 5 2 4 6]

[1 2 3 4 5 6]


MATRIX

In [70]:
x = np.matrix([[1,2,3],[1,2,3]])
print(x)

[[1 2 3]
 [1 2 3]]


In [71]:
type(x)

numpy.matrix

In [72]:
x1 = np.matrix([[1,2],[3,4]])
x2 = np.matrix([[1,2],[3,4]])

print(x1.dot(x2))

[[ 7 10]
 [15 22]]


In [73]:
print(x1.transpose())

[[1 3]
 [2 4]]


In [75]:
print(np.linalg.inv(x1))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [81]:
np.linalg.matrix_power(x1,1)

matrix([[1, 2],
        [3, 4]])